### PR TITLE
Fix initial e2e run issue #99

### LINKED ISSUE #99: fix initial e2e-test failure in make test-e2e
fix initial e2e-test failure in make test-e2e
~~~
[akaris@linux ingress-node-firewall (sdn-3315)]$ make test-e2e
/home/akaris/development/ingress-node-firewall/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
==== Generating DaemonSet manifest
hack/generate-daemon-manifest.sh
/home/akaris/development/ingress-node-firewall/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
rm -rf /tmp/test_validation_logs/
mkdir -p /tmp/test_validation_logs/
go test --tags=validationtests -v ./test/e2e/validation -ginkgo.v -junit /tmp/test_validation_logs/ -report /tmp/test_validation_logs/ 
=== RUN   TestValidation
Running Suite: Ingress Node Firewall Operator Validation Suite
==============================================================
Random Seed: 1660219716
Will run 4 of 4 specs

IngressNodeFirewall IngressNodeFirewall 
  should have the IngressNodeFirewall Operator deployment in running state
  /home/akaris/development/ingress-node-firewall/test/e2e/validation/tests/validation.go:30
•
------------------------------
IngressNodeFirewall IngressNodeFirewall 
  should have the IngressNodeFirewallConfig CRD available in the cluster
  /home/akaris/development/ingress-node-firewall/test/e2e/validation/tests/validation.go:52
•
------------------------------
IngressNodeFirewall IngressNodeFirewall 
  should have the IngressNodeFirewall CRD available in the cluster
  /home/akaris/development/ingress-node-firewall/test/e2e/validation/tests/validation.go:58
•
------------------------------
IngressNodeFirewall IngressNodeFirewall 
  should have the IngressNodeFirewallNodeState CRD available in the cluster
  /home/akaris/development/ingress-node-firewall/test/e2e/validation/tests/validation.go:64
•
JUnit report was created: /tmp/test_validation_logs/validation_junit.xml

Ran 4 of 4 Specs in 0.039 seconds
SUCCESS! -- 4 Passed | 0 Failed | 0 Pending | 0 Skipped

You're using deprecated Ginkgo functionality:
=============================================
Ginkgo 2.0 is under active development and will introduce several new features, improvements, and a small handful of breaking changes.
A release candidate for 2.0 is now available and 2.0 should GA in Fall 2021.  Please give the RC a try and send us feedback!
  - To learn more, view the migration guide at https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md
  - For instructions on using the Release Candidate visit https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#using-the-beta
  - To comment, chime in at https://github.com/onsi/ginkgo/issues/711

  You are using a custom reporter.  Support for custom reporters will likely be removed in V2.  Most users were using them to generate junit or teamcity reports and this functionality will be merged into the core reporter.  In addition, Ginkgo 2.0 will support emitting a JSON-formatted report that users can then manipulate to generate custom reports.

  If this change will be impactful to you please leave a comment on https://github.com/onsi/ginkgo/issues/711
  Learn more at: https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#removed-custom-reporters

To silence deprecations that can be silenced set the following environment variable:
  ACK_GINKGO_DEPRECATIONS=1.16.5

--- PASS: TestValidation (0.07s)
PASS
ok  	github.com/openshift/ingress-node-firewall/test/e2e/validation	0.186s
rm -rf /tmp/test_e2e_logs/
mkdir -p /tmp/test_e2e_logs/
go test --tags=e2etests -v ./test/e2e/functional -ginkgo.v -junit /tmp/test_e2e_logs/ -report /tmp/test_e2e_logs/ 
=== RUN   TestE2E
Running Suite: Ingress Node Firewall Operator E2E Suite
=======================================================
Random Seed: 1660219719
Will run 16 of 16 specs

Ingress Node Firewall IngressNodeFirewall deploy 
  should run Ingress node firewall DaemonSet
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:70
STEP: checking Ingress node firewall daemonset is in running state

• [SLOW TEST:8.147 seconds]
Ingress Node Firewall
/home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:38
  IngressNodeFirewall deploy
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:39
    should run Ingress node firewall DaemonSet
    /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:70
------------------------------
Ingress Node Firewall IngressNodeFirewall deploy 
  should run Ingress node firewall apply rules and check the actions
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:94
STEP: get nodes IP addresses with matching labels and ping their IPs
STEP: creating ingress node firewall rules
STEP: checking Ingress node firewall rules resource is created
STEP: checking ingress node firewall nodeState resource is created
STEP: checking Ingress node firewall rules deny ping packets
STEP: checking ingress node firewall events are generated
STEP: checking Ingress node firewall nodeState resource is deleted
STEP: checking Ingress node firewall rules resource is deleted

• [SLOW TEST:32.421 seconds]
Ingress Node Firewall
/home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:38
  IngressNodeFirewall deploy
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:39
    should run Ingress node firewall apply rules and check the actions
    /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:94
------------------------------
Ingress Node Firewall Statistics 
  should expose at least one endpoint via a daemon metrics service
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:258

• [SLOW TEST:5.059 seconds]
Ingress Node Firewall
/home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:38
  Statistics
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:227
    should expose at least one endpoint via a daemon metrics service
    /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:258
------------------------------
Ingress Node Firewall Statistics 
  should expose daemon metrics
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:285

• [SLOW TEST:39.396 seconds]
Ingress Node Firewall
/home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:38
  Statistics
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:227
    should expose daemon metrics
    /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:285
------------------------------
Ingress Node Firewall Webhook 
  should allow valid ingressnodefirewall TCP rule
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:425
•
------------------------------
Ingress Node Firewall Webhook 
  should allow valid ingressnodefirewall UDP rule
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:434
•
------------------------------
Ingress Node Firewall Webhook 
  should allow valid ingressnodefirewall ICMPV4 rule
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:443
•
------------------------------
Ingress Node Firewall Webhook 
  should allow valid ingressnodefirewall ICMPV6 rule
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:452
•
------------------------------
Ingress Node Firewall Webhook 
  should allow valid ingressnodefirewall SCTP rule
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:461
•
------------------------------
Ingress Node Firewall Webhook 
  should block any rules which conflict with failsafe rules
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:470
•
------------------------------
Ingress Node Firewall Webhook 
  should block invalid order
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:487

• Failure in Spec Teardown (AfterEach) [0.012 seconds]
Ingress Node Firewall
/home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:38
  Webhook
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:394
    should block invalid order [AfterEach]
    /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:487

    Unexpected error:
        <*errors.StatusError | 0xc0005cc780>: {
            ErrStatus: {
                TypeMeta: {Kind: "", APIVersion: ""},
                ListMeta: {
                    SelfLink: "",
                    ResourceVersion: "",
                    Continue: "",
                    RemainingItemCount: nil,
                },
                Status: "Failure",
                Message: "daemonsets.apps \"ingress-node-firewall-daemon\" not found",
                Reason: "NotFound",
                Details: {
                    Name: "ingress-node-firewall-daemon",
                    Group: "apps",
                    Kind: "daemonsets",
                    UID: "",
                    Causes: nil,
                    RetryAfterSeconds: 0,
                },
                Code: 404,
            },
        }
        daemonsets.apps "ingress-node-firewall-daemon" not found
    occurred

    /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:417
------------------------------
Ingress Node Firewall Webhook 
  should block TCP rule ICMP defined
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:497
•
------------------------------
Ingress Node Firewall Webhook 
  should block UDP rule ICMP defined
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:506
•
------------------------------
Ingress Node Firewall Webhook 
  should block SCTP rule ICMP defined
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:515
•
------------------------------
Ingress Node Firewall Webhook 
  should block ICMPV4 with TCP port defined
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:524
•
------------------------------
Ingress Node Firewall Webhook 
  should block ICMPV6 with TCP port defined
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:533
•
JUnit report was created: /tmp/test_e2e_logs/e2e_junit.xml


Summarizing 1 Failure:

[Fail] Ingress Node Firewall Webhook [AfterEach] should block invalid order 
/home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:417

Ran 16 of 16 Specs in 109.838 seconds
FAIL! -- 15 Passed | 1 Failed | 0 Pending | 0 Skipped

You're using deprecated Ginkgo functionality:
=============================================
Ginkgo 2.0 is under active development and will introduce several new features, improvements, and a small handful of breaking changes.
A release candidate for 2.0 is now available and 2.0 should GA in Fall 2021.  Please give the RC a try and send us feedback!
  - To learn more, view the migration guide at https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md
  - For instructions on using the Release Candidate visit https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#using-the-beta
  - To comment, chime in at https://github.com/onsi/ginkgo/issues/711

  You are using a custom reporter.  Support for custom reporters will likely be removed in V2.  Most users were using them to generate junit or teamcity reports and this functionality will be merged into the core reporter.  In addition, Ginkgo 2.0 will support emitting a JSON-formatted report that users can then manipulate to generate custom reports.

  If this change will be impactful to you please leave a comment on https://github.com/onsi/ginkgo/issues/711
  Learn more at: https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#removed-custom-reporters

To silence deprecations that can be silenced set the following environment variable:
  ACK_GINKGO_DEPRECATIONS=1.16.5

--- FAIL: TestE2E (109.86s)
FAIL
FAIL	github.com/openshift/ingress-node-firewall/test/e2e/functional	109.938s
FAIL
make: *** [Makefile:134: test-functional] Error 1
[akaris@linux ingress-node-firewall (sdn-3315)]$ make test-e2e
/home/akaris/development/ingress-node-firewall/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
==== Generating DaemonSet manifest
hack/generate-daemon-manifest.sh
/home/akaris/development/ingress-node-firewall/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
rm -rf /tmp/test_validation_logs/
mkdir -p /tmp/test_validation_logs/
go test --tags=validationtests -v ./test/e2e/validation -ginkgo.v -junit /tmp/test_validation_logs/ -report /tmp/test_validation_logs/ 
=== RUN   TestValidation
Running Suite: Ingress Node Firewall Operator Validation Suite
==============================================================
Random Seed: 1660219843
Will run 4 of 4 specs

IngressNodeFirewall IngressNodeFirewall 
  should have the IngressNodeFirewall Operator deployment in running state
  /home/akaris/development/ingress-node-firewall/test/e2e/validation/tests/validation.go:30
•
------------------------------
IngressNodeFirewall IngressNodeFirewall 
  should have the IngressNodeFirewallConfig CRD available in the cluster
  /home/akaris/development/ingress-node-firewall/test/e2e/validation/tests/validation.go:52
•
------------------------------
IngressNodeFirewall IngressNodeFirewall 
  should have the IngressNodeFirewall CRD available in the cluster
  /home/akaris/development/ingress-node-firewall/test/e2e/validation/tests/validation.go:58
•
------------------------------
IngressNodeFirewall IngressNodeFirewall 
  should have the IngressNodeFirewallNodeState CRD available in the cluster
  /home/akaris/development/ingress-node-firewall/test/e2e/validation/tests/validation.go:64
•
JUnit report was created: /tmp/test_validation_logs/validation_junit.xml

Ran 4 of 4 Specs in 0.040 seconds
SUCCESS! -- 4 Passed | 0 Failed | 0 Pending | 0 Skipped

You're using deprecated Ginkgo functionality:
=============================================
Ginkgo 2.0 is under active development and will introduce several new features, improvements, and a small handful of breaking changes.
A release candidate for 2.0 is now available and 2.0 should GA in Fall 2021.  Please give the RC a try and send us feedback!
  - To learn more, view the migration guide at https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md
  - For instructions on using the Release Candidate visit https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#using-the-beta
  - To comment, chime in at https://github.com/onsi/ginkgo/issues/711

  You are using a custom reporter.  Support for custom reporters will likely be removed in V2.  Most users were using them to generate junit or teamcity reports and this functionality will be merged into the core reporter.  In addition, Ginkgo 2.0 will support emitting a JSON-formatted report that users can then manipulate to generate custom reports.

  If this change will be impactful to you please leave a comment on https://github.com/onsi/ginkgo/issues/711
  Learn more at: https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#removed-custom-reporters

To silence deprecations that can be silenced set the following environment variable:
  ACK_GINKGO_DEPRECATIONS=1.16.5

--- PASS: TestValidation (0.06s)
PASS
ok  	github.com/openshift/ingress-node-firewall/test/e2e/validation	0.114s
rm -rf /tmp/test_e2e_logs/
mkdir -p /tmp/test_e2e_logs/
go test --tags=e2etests -v ./test/e2e/functional -ginkgo.v -junit /tmp/test_e2e_logs/ -report /tmp/test_e2e_logs/ 
=== RUN   TestE2E
Running Suite: Ingress Node Firewall Operator E2E Suite
=======================================================
Random Seed: 1660219845
Will run 16 of 16 specs

Ingress Node Firewall IngressNodeFirewall deploy 
  should run Ingress node firewall DaemonSet
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:70
STEP: checking Ingress node firewall daemonset is in running state
•
------------------------------
Ingress Node Firewall IngressNodeFirewall deploy 
  should run Ingress node firewall apply rules and check the actions
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:94
STEP: get nodes IP addresses with matching labels and ping their IPs
STEP: creating ingress node firewall rules
STEP: checking Ingress node firewall rules resource is created
STEP: checking ingress node firewall nodeState resource is created
STEP: checking Ingress node firewall rules deny ping packets
STEP: checking ingress node firewall events are generated
STEP: checking Ingress node firewall nodeState resource is deleted
STEP: checking Ingress node firewall rules resource is deleted

• [SLOW TEST:28.268 seconds]
Ingress Node Firewall
/home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:38
  IngressNodeFirewall deploy
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:39
    should run Ingress node firewall apply rules and check the actions
    /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:94
------------------------------
Ingress Node Firewall Statistics 
  should expose at least one endpoint via a daemon metrics service
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:258
•
------------------------------
Ingress Node Firewall Statistics 
  should expose daemon metrics
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:285

• [SLOW TEST:34.544 seconds]
Ingress Node Firewall
/home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:38
  Statistics
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:227
    should expose daemon metrics
    /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:285
------------------------------
Ingress Node Firewall Webhook 
  should allow valid ingressnodefirewall TCP rule
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:425
•
------------------------------
Ingress Node Firewall Webhook 
  should allow valid ingressnodefirewall UDP rule
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:434
•
------------------------------
Ingress Node Firewall Webhook 
  should allow valid ingressnodefirewall ICMPV4 rule
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:443
•
------------------------------
Ingress Node Firewall Webhook 
  should allow valid ingressnodefirewall ICMPV6 rule
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:452
•
------------------------------
Ingress Node Firewall Webhook 
  should allow valid ingressnodefirewall SCTP rule
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:461
•
------------------------------
Ingress Node Firewall Webhook 
  should block any rules which conflict with failsafe rules
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:470
•
------------------------------
Ingress Node Firewall Webhook 
  should block invalid order
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:487
•
------------------------------
Ingress Node Firewall Webhook 
  should block TCP rule ICMP defined
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:497
•
------------------------------
Ingress Node Firewall Webhook 
  should block UDP rule ICMP defined
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:506
•
------------------------------
Ingress Node Firewall Webhook 
  should block SCTP rule ICMP defined
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:515
•
------------------------------
Ingress Node Firewall Webhook 
  should block ICMPV4 with TCP port defined
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:524
•
------------------------------
Ingress Node Firewall Webhook 
  should block ICMPV6 with TCP port defined
  /home/akaris/development/ingress-node-firewall/test/e2e/functional/tests/e2e.go:533
•
JUnit report was created: /tmp/test_e2e_logs/e2e_junit.xml

Ran 16 of 16 Specs in 65.509 seconds
SUCCESS! -- 16 Passed | 0 Failed | 0 Pending | 0 Skipped

You're using deprecated Ginkgo functionality:
=============================================
Ginkgo 2.0 is under active development and will introduce several new features, improvements, and a small handful of breaking changes.
A release candidate for 2.0 is now available and 2.0 should GA in Fall 2021.  Please give the RC a try and send us feedback!
  - To learn more, view the migration guide at https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md
  - For instructions on using the Release Candidate visit https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#using-the-beta
  - To comment, chime in at https://github.com/onsi/ginkgo/issues/711

  You are using a custom reporter.  Support for custom reporters will likely be removed in V2.  Most users were using them to generate junit or teamcity reports and this functionality will be merged into the core reporter.  In addition, Ginkgo 2.0 will support emitting a JSON-formatted report that users can then manipulate to generate custom reports.

  If this change will be impactful to you please leave a comment on https://github.com/onsi/ginkgo/issues/711
  Learn more at: https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#removed-custom-reporters

To silence deprecations that can be silenced set the following environment variable:
  ACK_GINKGO_DEPRECATIONS=1.16.5

--- PASS: TestE2E (65.53s)
PASS
ok  	github.com/openshift/ingress-node-firewall/test/e2e/functional	65.603s
~~~

### PR DESCRIPTION
**Pull request by msherif1234**
Fix #99 
- allow some waiting time for rules delete to complete.
- remove webhook test cases that are now not allowed by the APIs.

here is what the API verify for us:
- for order 0 we will get this error
```
The IngressNodeFirewall "ingressnodefirewall-demo2" is invalid: spec.ingress[0].rules[0].order: Invalid value: 0: spec.ingress[0].rules[0].order in body should be greater than or equal to 1
```
- for mixed protocol case we will get
```
* spec.ingress[0][rules][0]: Invalid value: "ingressnodefirewall-demo2": must be a valid TCP rule: no port defined
* spec.ingress[0][rules][1]: Invalid value: "ingressnodefirewall-demo2": must be a valid ICMP(V6) rule: no ICMP rules defined. Define icmpType/icmpCode
```
here is fresh e2e run after cluster is created after adding the wait to make sure rules are deleted
```
Ran 10 of 10 Specs in 198.667 seconds
SUCCESS! -- 10 Passed | 0 Failed | 0 Pending | 0 Skipped
```
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>

### CODE REVIEW

File: controllers/ingressnodefirewall_controller.go [hunk 1]
```diff
@@ -362,10 +367,7 @@ func (r *IngressNodeFirewallReconciler) buildNodeStates(
 }
 
 func isLegalInterfaceName(iface string) bool {
```
Comment (andreaskaris) [inline controllers/ingressnodefirewall_controller.go:369]: nit, but whatever you prefer.

Perhaps just write this as:
~~~
var isLegalInterfaceName = func(iface string) bool {
~~~

That way, it's already a variable and line 50 isn't needed

File: controllers/ingressnodefirewall_controller.go [hunk 2]
```diff
@@ -362,10 +367,7 @@ func (r *IngressNodeFirewallReconciler) buildNodeStates(
...
-	if iface == "" {
-		return false
-	}
-	return true
+	return interfaces.IsValidInterfaceNameAndState(iface)
```
Comment (andreaskaris) [inline controllers/ingressnodefirewall_controller.go:370]: isLegalInterfaceName runs as part of the IngressNodeFirewallReconsiler which is part of the operator pod. But the operator can't do a local lookup for valid interfaces names. 
a) the operator runs without host network
b) even if it did, the interfaces on the operator's host might be different from those on the other hosts. 

So I think here we need a very generic verificatoin for valid syntax for interface names. And then inside the ingressnodefirewallnodestate controller that runs inside the daemon we need a check for IsValidInterfaceNameAndState. If that there returns false, we must post a status to the NodeState resource or emit an event or something else.

File: test/e2e/functional/tests/e2e.go [hunk 3]
```diff
@@ -428,7 +421,13 @@ var _ = Describe("Ingress Node Firewall", func() {
 			infwutils.DefineWithInterface(inf, "eth0")
 			infwutils.DefineDenyTCPRule(inf, "1.1.1.1/32", 40000)
 			Expect(testclient.Client.Create(context.Background(), inf)).To(Succeed())
-			Expect(testclient.Client.Delete(context.Background(), inf)).To(Succeed())
+			Eventually(func() bool {
```
Comment (andreaskaris) [inline test/e2e/functional/tests/e2e.go:424]: move this green block into a small helper functoin and then call this as a one liner to avoid code duplication?

File: controllers/ingressnodefirewall_controller.go (hunk 2 above)
Comment (msherif1234) [reply controllers/ingressnodefirewall_controller.go]: I moved the check to the daemon pkg and return an error when condition is detected

Comment (msherif1234) [reply controllers/ingressnodefirewall_controller.go]: I moved that check to the webhook and added more check to make sure is legit interface(s) name

File: controllers/ingressnodefirewall_controller.go (hunk 1 above)
Comment (msherif1234) [reply controllers/ingressnodefirewall_controller.go]: removed that code

File: pkg/webhook/webhook.go [hunk 4]
```diff
@@ -75,9 +76,37 @@ func validateIngressNodeFirewall(ctx context.Context, inf *ingressnodefwv1alpha1
...
 }
 
+func validateINFInterfaces(ctx context.Context, infInterfaces []string, infName string, kubeClient client.Client) field.ErrorList {
+	var allErrs field.ErrorList
+
+	for idx, inf := range infInterfaces {
+		if inf == "" {
+			allErrs = append(allErrs,
+				field.Invalid(field.NewPath("spec").Child("interfaces").Index(idx).Key("interaces"),
+					infName, fmt.Sprintf("must be valid interface names %s", inf)))
```
Comment (martinkennelly) [inline pkg/webhook/webhook.go:94]: Maybe let the user know blank interfaces arent ok - printing out the black inf is pointless.

File: pkg/webhook/webhook.go [hunk 5]
```diff
@@ -75,9 +76,37 @@ func validateIngressNodeFirewall(ctx context.Context, inf *ingressnodefwv1alpha1
...
+		}
+		if len(inf) > unix.IFNAMSIZ {
+			allErrs = append(allErrs,
+				field.Invalid(field.NewPath("spec").Child("interfaces").Index(idx).Key("interaces"),
```
Comment (martinkennelly) [inline pkg/webhook/webhook.go:98]: drop the key here too.

File: pkg/webhook/webhook.go [hunk 6]
```diff
@@ -75,9 +76,37 @@ func validateIngressNodeFirewall(ctx context.Context, inf *ingressnodefwv1alpha1
...
+					infName, fmt.Sprintf("interface name is too long %s", inf)))
+		}
+		if inf[0] >= '0' && inf[0] <= '9' {
+			allErrs = append(allErrs,
+				field.Invalid(field.NewPath("spec").Child("interfaces").Index(idx).Key("interaces"),
+					infName, fmt.Sprintf("interface name can't starts with numbers %s", inf)))
```
Comment (martinkennelly) [inline pkg/webhook/webhook.go:104]:
```suggestion
					infName, fmt.Sprintf("interface %q can't start with a number", inf)))
```

**Comment by martinkennelly** [comment]
Following correction of above, it lgtm.

File: controllers/ingressnodefirewall_controller.go [hunk 7]
```diff
@@ -324,17 +323,6 @@ func (r *IngressNodeFirewallReconciler) buildNodeStates(
 				continue withNextNode
 			}
 			for _, iface := range firewallObj.Spec.Interfaces {
-				// Verify if an invalid interface name was specified.
-				// On error, report the error in the status field and continue with the next node.
-				if !isLegalInterfaceName(iface) {
```
Comment (andreaskaris) [inline controllers/ingressnodefirewall_controller.go:329]: I have a feeling that this will break one of the unit tests but if it does I'll fix it in my PR

Comment (msherif1234) [reply controllers/ingressnodefirewall_controller.go:329]: no unit-test is passing fine I unless it flakes ?
