### PR TITLE
Interfaces validation pkg

### LINKED ISSUE #91: Make sure to check valid interfaces names instead of crashing
This must go into the daemon (because that's the only entity that know that available interface names) and we must post an event / update the NodeState if an invalid interfaces name is specified

### PR DESCRIPTION
**Pull request by msherif1234**
before attaching XDP to interfaces we need to make
sure interfaces are valid and in the right state
fixed #91 
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>

### CODE REVIEW

File: pkg/utils/interfaces_test.go [hunk 1]
```diff
@@ -0,0 +1,36 @@
+package utils
```
Comment (andreaskaris) [inline pkg/utils/interfaces_test.go:1]: For the test, it might be nice to make it mockable and not depend on actual values from the system, something like:
https://stackoverflow.com/questions/68940230/how-to-mock-net-interface
